name:                demo-custom-exceptions
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- sandwich
- text
- time

when:
- condition: "!os(windows)"
  dependencies:
  - brick
  - vty


default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-custom-exceptions:
    main: Main.hs
    source-dirs: app
