
resolver: lts-17.5

packages:
- ./sandwich
- ./sandwich-demos
- ./sandwich-quickcheck
- ./sandwich-slack
- ./sandwich-webdriver

extra-deps:
# Because upstream hs-webdriver has a few bugs and seems unmaintained
- git: https://github.com/codedownio/hs-webdriver
  commit: 96400ea0ba6ef118033d6a727ef4f57c31a187ca
