name:                sandwich-hedgehog
version:             0.1.2.0
github:              "codedownio/sandwich-hedgehog"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2023 Tom McLaughlin"
category:            Testing
homepage:            https://codedownio.github.io/sandwich
synopsis:            Sandwich integration with Hedgehog
description:         Please see the <https://codedownio.github.io/sandwich/docs/extensions/sandwich-hedgehog documentation>.

extra-source-files:
- ChangeLog.md

dependencies:
- base < 5
- free
- hedgehog
- monad-control
- mtl
- safe-exceptions
- sandwich >= 0.1.0.4
- string-interpolate
- text
- time
- wl-pprint-annotated

when:
- condition: "!os(windows)"
  dependencies:
  - vty

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

library:
  source-dirs: src
  exposed-modules:
    - Test.Sandwich.Hedgehog
  when:
  - condition: "!os(windows)"
    source-dirs: unix-src

tests:
  sandwich-hedgehog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
