name:                demo-stack-test
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- sandwich

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

tests:
  demo-stack-test:
    main: Main.hs
    source-dirs: app
