name:                sandwich
version:             0.1.0.0
github:              "githubuser/sandwich"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "example@example.com"
copyright:           "2021 Tom McLaughlin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sandwich#readme>

dependencies:
- aeson
- ansi-terminal
- async
- base
- colour
- containers
- brick
- bytestring
- directory
- exceptions
- filepath
- free
- lens
- lifted-async
- microlens
- microlens-th
- monad-control
- monad-logger
- mtl
- optparse-applicative
- pretty-show
- process
- safe
- safe-exceptions
- stm
- string-interpolate
- template-haskell
- text
- time
- transformers
- transformers-base
- unliftio-core
- unix
- vector
- vty

library:
  source-dirs: src
  ghc-options:
  - -W
  exposed-modules:
    - Test.Sandwich
    - Test.Sandwich.Contexts
    - Test.Sandwich.Expectations
    - Test.Sandwich.Logging
    - Test.Sandwich.Nodes
    - Test.Sandwich.Options
    - Test.Sandwich.Formatters.FailureReport
    - Test.Sandwich.Formatters.LogSaver
    - Test.Sandwich.Formatters.Print
    - Test.Sandwich.Formatters.TerminalUI
    - Test.Sandwich.Internal
    - Test.Sandwich.Internal.Formatters

executables:
  sandwich-exe:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

  sandwich-discover:
    main: Main.hs
    source-dirs:
    - discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

  sandwich-test:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

tests:
  sandwich-test-suite:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich
