name:                sandwich-demos
version:             0.1.0.0
github:              "githubuser/sandwich-demos"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "example@example.com"
copyright:           "2020 Tom McLaughlin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sandwich-demos#readme>

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- containers
- convertible
- data-default
- directory
- exceptions
- filepath
- http-client
- http-conduit
- interpolate
- lifted-base
- monad-control
- monad-logger
- mtl
- network
- process
- random
- retry
- safe
- safe-exceptions
- sandwich
- temporary
- text
- time
- transformers
- transformers-base
- unix
- unordered-containers

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

executables:
  tui-demo:
    main:                TUI.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
