name:                sandwich-demos
version:             0.1.0.0
github:              "githubuser/sandwich-demos"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "example@example.com"
copyright:           "2020 Tom McLaughlin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sandwich-demos#readme>

dependencies:
- base
- exceptions
- filepath
- lifted-base
- monad-control
- random
- sandwich
- sandwich-slack
- string-interpolate
- time

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: lib

executables:
  basic:
    main: Main.hs
    source-dirs: demos/basic
    dependencies:
    - sandwich-demos

  contexts:
    main: Main.hs
    source-dirs: demos/contexts
    dependencies:
    - sandwich-demos

  context-dependencies:
    main: Main.hs
    source-dirs: demos/context-dependencies
    dependencies:
    - sandwich-demos

  context-nested-dependencies:
    main: Main.hs
    source-dirs: demos/context-nested-dependencies
    dependencies:
    - sandwich-demos

  discover:
    main: Main.hs
    source-dirs: demos/discover

  landing:
    main: Main.hs
    source-dirs: demos/landing
    dependencies:
    - sandwich-demos

  quickcheck:
    main: Main.hs
    source-dirs: demos/quickcheck
    dependencies:
    - QuickCheck

  tui:
    main: Main.hs
    source-dirs: demos/tui
    dependencies:
    - sandwich-demos

  timing:
    main: Main.hs
    source-dirs: demos/timing
    dependencies:
    - sandwich-demos

  timing-parallel:
    main: Main.hs
    source-dirs: demos/timing-parallel
    dependencies:
    - sandwich-demos

