name:                demo-context-nested-dependencies
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- exceptions
- lifted-base
- monad-control
- random
- sandwich
- sandwich-demos
- string-interpolate
- time

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: lib

executables:
  demo-context-nested-dependencies:
    main: Main.hs
    source-dirs: app
