name:                sandwich-quickcheck
version:             0.1.0.4
github:              "codedownio/sandwich-quickcheck"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2021 Tom McLaughlin"
category:            Testing
homepage:            https://codedownio.github.io/sandwich
synopsis:            Sandwich integration with QuickCheck
description:         Please see the <https://codedownio.github.io/sandwich/docs/extensions/sandwich-quickcheck documentation>.

extra-source-files:
- ChangeLog.md

dependencies:
- base < 4.15
- free
- monad-control
- QuickCheck
- safe-exceptions
- sandwich >= 0.1.0.4
- string-interpolate
- time

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

library:
  source-dirs: src

executables:
  sandwich-quickcheck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich-quickcheck

tests:
  sandwich-quickcheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich-quickcheck
