name:                sandwich-quickcheck
version:             0.1.0.0
github:              "githubuser/sandwich-quickcheck"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "example@example.com"
copyright:           "2021 Tom McLaughlin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sandwich-quickcheck#readme>

dependencies:
- aeson
- async
- base
- containers
- convertible
- data-default
- directory
- exceptions
- filepath
- http-client
- http-conduit
- lifted-base
- monad-control
- monad-logger
- mtl
- network
- process
- QuickCheck
- random
- retry
- safe
- safe-exceptions
- sandwich
- string-interpolate
- temporary
- text
- time
- transformers
- transformers-base
- unix
- unordered-containers

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

library:
  source-dirs: src

executables:
  sandwich-quickcheck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich-quickcheck
    - time

tests:
  sandwich-quickcheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich-quickcheck
